# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Install dependencies
      run: go mod tidy

    - name: Run Linter
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest

    - name: Build
      run: go build ./...

    - name: Run Unit Tests with Coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.out
